theme: minima
title: Some many questions ... and everybody belives to have the answer!
author: Ulrike from inner space
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This side questions everything, just to be annoying ...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
